### ISSUE TITLE
[TODO] Set up Sphinx documentation system

### ISSUE THREAD

**Issue by Simran-B** [sobotka/olive#111]
**General TODO Summary**

Start working on user docs & integrate code documentation

**Additional Information / Notes**

- [ ] Basic setup of Sphinx + maintainer readme
   https://github.com/olive-editor/olive/pull/1142
- [ ] Draft a first content structure
- [ ] Move content from main repo Wiki, which will then act as scratchpad for collaborators (not user facing anymore; add link from wiki to docs)
- [ ] Integrate doxygen via breathe
- [ ] ~Register and set up hosting for readthedocs (RTD)~
- [ ] Configure automation (CI builds of docs including doxygen) and make the system ready for others to use
- [ ] Create GitHub Actions workflow to deploy to website
- [ ] Add link to homepage / navigation

**Comment by Simran-B** [comment]
The plan is to publish docs to https://olivevideoeditor.org/, where we can embed ads at our own discretion, unlike with RTD.

Need to decide on how to upload to website (e.g. Curl push + unpack + switch out files, or GHA tickle + Git pull on server)

Also need to decide the URL under which it will be available, e.g. https://olivevideoeditor.org/docs

**Comment by Simran-B** [comment]
May not use Sphinx/Doxygen after all, but there is a WIP PR here: https://github.com/olive-editor/olive/pull/1142
